# Generated by Django 2.2.2 on 2020-05-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcodex_bible", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bibleverse",
            name="char_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bibleverse",
            name="word_count",
            field=models.IntegerField(default=0),
        ),
    ]
