# Generated by Django 3.1.3 on 2021-02-16 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_bible', '0002_auto_20200529_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biblemanuscript',
            options={},
        ),
    ]
