# Generated by Django 3.1.3 on 2021-02-16 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_bible', '0003_auto_20210216_0331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biblemanuscript',
            options={'base_manager_name': 'objects'},
        ),
    ]
