# Generated by Django 3.2.9 on 2021-12-09 23:29

from django.db import migrations
from django.db.models import F
from dcodex_bible.models import BibleVerse

def add_doxology(apps, schema_editor):
    """ Adds in verses for doxology at the end of Romans 14. """
    try:
        romans_14_end = BibleVerse.get_from_string("Romans 14:99")
    except Exception:
        return

    # Check if see if it ends at 14:23 which is incorrect
    if romans_14_end.verse == 23:
        # https://github.com/byztxt/byzantine-majority-text/blob/master/csv-unicode/no-variants/RO.csv
        new_verses = [
            "Ὁ δὲ διακρινόμενος, ἐὰν φάγῃ, κατακέκριται, ὅτι οὐκ ἐκ πίστεως· πᾶν δὲ ὃ οὐκ ἐκ πίστεως, ἁμαρτία ἐστίν.",
            "Τῷ δὲ δυναμένῳ ὑμᾶς στηρίξαι κατὰ τὸ εὐαγγέλιόν μου καὶ τὸ κήρυγμα Ἰησοῦ χριστοῦ, κατὰ ἀποκάλυψιν μυστηρίου χρόνοις αἰωνίοις σεσιγημένου,",
            "μόνῳ σοφῷ θεῷ, διὰ Ἰησοῦ χριστοῦ, ᾧ ἡ δόξα εἰς τοὺς αἰῶνας. Ἀμήν.",
        ]

        # Bump rank for later verses
        verses_to_bump = BibleVerse.objects.filter(rank__gt=romans_14_end.rank)
        new_chars = 0
        new_words = 0
        for verse in new_verses:
            new_chars += len(verse)
            new_words += len(verse.split())

        verses_to_bump.update(rank=F('rank')+len(new_verses), char_aggregate=F('char_aggregate')+new_chars, word_aggregate=F('word_aggregate')+new_words)

        # Create new verses
        char_aggregate = romans_14_end.char_aggregate + romans_14_end.char_count
        word_aggregate = romans_14_end.word_aggregate + romans_14_end.word_count
        for index, verse in enumerate(new_verses):
            word_count = len(verse.split())
            char_count = len(verse)
            BibleVerse.objects.create(
                book=romans_14_end.book, 
                chapter=romans_14_end.chapter, 
                verse=romans_14_end.verse + 1 + index, 
                rank=romans_14_end.rank + 1 + index,
                word_count=word_count,
                char_count=char_count,
                char_aggregate=char_aggregate,
                word_aggregate=word_aggregate,
            )
            char_aggregate += char_count
            word_aggregate += word_count


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_bible', '0005_nestlealandmarkup'),
    ]

    operations = [
        migrations.RunPython(add_doxology),
    ]
